/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import java.util.ArrayList;
import java.util.List;

import javafx.application.Application;
import javafx.beans.binding.Bindings;
import javafx.beans.property.ReadOnlyStringWrapper;
import javafx.beans.property.SimpleStringProperty;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TextField;
import javafx.scene.control.TableView;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.RowConstraints;
import javafx.stage.Stage;

public class ContatoBoundary extends Application {

    private ContatoControl control = new ContatoControl();
    private TextField txtNome = new TextField();
    private TextField txtTelefone = new TextField();
    private TextField txtEmail = new TextField();
    private DatePicker dtaNascimento = new DatePicker();
    private TableView<Contato> tabela = new TableView<>();

    public void bindings() { 
        Bindings.bindBidirectional(control.nomeProperty(), txtNome.textProperty());
        Bindings.bindBidirectional(control.telefoneProperty(), txtTelefone.textProperty());
        Bindings.bindBidirectional(control.emailProperty(), txtEmail.textProperty());
        Bindings.bindBidirectional(control.nascimentoProperty(), dtaNascimento.valueProperty());
    }

    public void tableCreation() {
        TableColumn<Contato, String> col1 = new TableColumn<>("Nome");
        col1.setCellValueFactory( c -> new ReadOnlyStringWrapper( c.getValue().getNome() ));

        tabela.getColumns().addAll( col1 );

        tabela.setItems( control.listaProperty() );
    }

    public void start(Stage stage) { 
        BorderPane panePrincipal = new BorderPane();
        GridPane paneForm = new GridPane();
        HBox paneBotoes = new HBox();

        // Faz as ligações entre propriedades do Control
        bindings();

        // Gera as colunas da tabela
        tableCreation();

        ColumnConstraints colLabel = new ColumnConstraints();
        colLabel.setPercentWidth(30);

        ColumnConstraints colTextField = new ColumnConstraints();
        colTextField.setPercentWidth(70);

        RowConstraints linha = new RowConstraints();
        linha.setPrefHeight(50);

        paneForm.getColumnConstraints().addAll(colLabel, colTextField);
        paneForm.getRowConstraints().addAll(linha, linha, linha, linha, linha);

        Scene scn = new Scene(panePrincipal, 800, 600);

        Label lblNome = new Label("Nome");
        lblNome.setStyle("-fx-background-color: 'yellow'; -fx-font-size: 25px; -fx-width: '100%'; -fx-height: '100%'; -fx-rotate: 45");
        paneForm.add( lblNome, 0, 0);
        paneForm.add( txtNome, 1, 0);
        paneForm.add( new Label("Telefone:"), 0, 1);
        paneForm.add( txtTelefone, 1, 1);
        paneForm.add( new Label("Email:"), 0, 2);
        paneForm.add( txtEmail, 1, 2);
        paneForm.add( new Label("Nascimento:"), 0, 3);
        paneForm.add( dtaNascimento, 1, 3);

        Button btnSalvar = new Button("Salvar");

        btnSalvar.setOnAction( evento -> {
            control.cadastrar();
            new Alert(AlertType.INFORMATION, 
                "Contato gravado com sucesso", 
                            ButtonType.OK).show();
        });

        Button btnPesquisar = new Button("Pesquisar");

        btnPesquisar.setOnAction( evento -> {
            control.pesquisarContato();
        });

        paneBotoes.getChildren().addAll(btnSalvar, btnPesquisar);

        paneForm.add( paneBotoes, 0, 4, 2, 1);

        panePrincipal.setTop( paneForm );
        panePrincipal.setCenter( tabela );

        stage.setScene(scn);
        stage.setTitle("Agenda de Contato");
        stage.show();
    }

    public static void main(String[] args) {
        Application.launch(ContatoBoundary.class, args);
    }
}
